### ISSUE TITLE
message content dendent decryption error (with correctly defined pass and salt)

### ISSUE THREAD

**Issue by mortedancer** [simplepush/simplepush-nodejs#1]
Not sure it is simplepush issue or aes-cbc under nodeJS crypto library, but specific message (unencrypted data + initialization vector) values can either cause decryption error or do not cause it. Following short example can be used to reproduce error/no error cases.
Cause randomly selected IV quite impossible to get equal messages in different transactions, first of all I replace 
	`let ivBytes = crypto.randomBytes(IV_LENGTH);`
with
	`let ivBytes = Buffer.from("30a4196e41629ab574b0854cc51b45d3","hex");`
so in all cases we now have following IV value
	30a4196e41629ab574b0854cc51b45d3
then call pusher with two arguments whith only 1 letter difference in message field
  `pusher.send({'key':YOUR_ID,'title': "Hello",'message':"TM", 'event':"any",'password':"3oacub",'salt':"buspur5f"},console.error)`

 ` pusher.send({'key':YOUR_ID,'title': "Hello",'message':"T", 'event':"any",'password':"3oacub",'salt':"buspur5f"},console.error)`

In both cases 
	from password and salt we have equal encryption key - 8ed5610878c581180c5f91ad50edb721, 
	iv now always 30a4196e41629ab574b0854cc51b45d3, 

but  1 case ("message":"TM") is always correctly processed on phone side with no errors
	2 case ("message":"T") always cause decryption error
	
Official version of nodeJS simplepush library with random IV and more complex title/message fields more often cause decryption error then could be successfully decrypted...

**Comment by tymm** [comment]
> Official version of nodeJS simplepush library with random IV and more complex title/message fields more often cause decryption error then could be successfully decrypted...

Before I dig deeper: are you sure that you passed the correct password and salt? I can't manage to get any decryption error with the nodeJS library (with a random IV). Could you give an example for what you mean with complex title/message fields?

**Comment by mortedancer** [comment]
Yup! I'm pretty sure it is not a result of incorrect settings, if so I would never got correctly decrypted messages, but I do and more over in first message I give reproduceable example to correctly define problem. Unfortunately I have no option to refresh salt as well as I can't directly see decryption procedure in details. Answering you question let me show less formal but more clear example
  
![simplepush](https://user-images.githubusercontent.com/1622644/146860703-4d0a1b35-a2f8-42e5-8b3d-fabea834600c.jpg)

Here we can see 5 messages which was sent one by one, in this case simplepush module was reinstalled (also I upgrade node version from 13 to latest 17, to be sure that old engine definitely not the issue) so IV is randomly selected (and there is no any changes in original simplepush for nodeJS module). Messages has unique numbers, password and salt as well as all parameters from "send" signature except "message" are identical, as a result 3 notification from 5 triggers "Decryption error", but messages number (2) and (3) was decrypted without any error. So to sum up all details:
There are some cases  when all controlled parameters of "send" function call are identical or very similar for set of messages, but by unknown reason, in some cases, I got decryption error. JS engine running under win10 and node version is 17 (as I mentioned before). If I may help to find out the reason of such behavior, fell free to ask any follow up questions or run tests.

**Comment by tymm** [comment]
The issue was that I forgot to make the base64 encoded data url safe.
Interestingly the base64 decoder on iOS had no problem decoding it anyway which made the issue hard to reproduce for me initially.
I updated the library to version 1.0.4 where I fixed the issue.

Thank you for your efforts! Feel free to contact me at contact@simplepush.io if you want a free Android lifetime license for Simplepush :)

**Comment by mortedancer** [comment]
Excuse me for reviving issue just to address so simple bug, but I'm sure it is the fastest way to offer "patch". When appling urlsafe replace action, you probably make kind of typo in first replace call

line 46: 
 `encryptedURLSafe = encrypted.replace(/-/g, '+').replace(/\//g, '_')`
                     but obviously  should be
 `encryptedURLSafe = encrypted.replace(/\+/g, '-').replace(/\//g, '_')`

so, to be clear, write way is not replacing '-' with '+' but vice versa replace '+' with '-', with this correction encryptyon works with no errors on android. 
Also I want to express my gratitude to you for this project and fast reaction, everything works just like a charm extreamly simple way to integrate instant notifications to any project with no 'headace'.

**Comment by tymm** [comment]
Thanks!
